config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    member do
      get "like", to: "posts#upvote"
      get "dislike", to: "posts#downvote"
    end
    resources :comments
  end

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_many :comments
  has_attached_file :image, styles: { medium: "700x500#", small: "350x250>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :commentss
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.create(params[:comment].permit(:content))
    @comment.user_id = current_user.id
    @comment.post_id = @post.id

    if @comment.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def show
    @comments = Comment.where(post_id: @post)
    @random_post = Post.where.not(id: @post).order("RANDOM()").first
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def upvote
    @post.upvote_by current_user
    redirect_back(fallback_location: root_path)
  end

  def downvote
    @post.downvote_by current_user
    redirect_back(fallback_location: root_path)
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :link, :description, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
  <%= f.input :content, label: "Reply to thread" %>
  <%= f.submit class: "button" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Showcase</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css" />
  </head>

  <body>
    <header>
      <div class="wrapper clearfix">
        <div id="logo">
          <%= link_to "Showcase", root_path %>
        </div>
        <nav>
          <% if user_signed_in? %>
            <%= link_to current_user.username, edit_user_registration_path %>
            <%= link_to "New", new_post_path, class: "button" %>
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "button" %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path, class: "button" %>
            <%= link_to "Sign Up", new_user_registration_path, class: "button" %>
          <% end %>
        </nav>

      </div>
    </header>

    <div class="wrapper">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :title %>
  <%= f.input :link %>
  <%= f.input :description %>
  <%= f.input :image %>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit Inspiration</h2>
<%= render 'form' %>

app/views/posts/index.html.erb
<% if user_signed_in? %>
  <p id="intro">
    Hello <%= current_user.username %>
    <br>
    <span>Share your inspiration and see what's inspiring others.</span>
  </p>
<% else %>
<p id="intro">
  Welcome
  <br>
  <span>Share your inspiration and see what's inspiring others.</span>
</p>
<% end %>

<div id="posts">
  <% @posts.each do |post| %>
    <div class="post">
      <div class="post-image">
        <%= link_to (image_tag post.image.url(:small)), post %>
      </div>
      <div class="post-content">
        <div class="title">
          <h2><%= link_to post.title, post %></h2>
        </div>
        <div class="data clearfix">
          <p class="username">
            Shared by <%= post.user.username %>
          </p>
          <p class="buttons">
            <span>
              <i class="fa fa-comments-o"></i>
              <%= post.comments.count %>
            </span>
            <span>
              <i class="fa fa-thumbs-o-up"></i>
              <%= post.get_upvotes.size %>
            </span>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="form-container">
  <h2>Add New Inspiration</h2>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post-show">
  <h1><%= @post.title %></h1>
  <p class="username">
    Shared by <%= @post.user.username %>
    about <%= time_ago_in_words(@post.created_at) %> ago
  </p>
  <div class="clearfix">
    <div class="post-image-description">
      <%= image_tag @post.image.url(:medium) %>
      <div class="description">
        <%= simple_format(@post.description) %>
      </div>
    </div>
    <div class="post-data">
      <%= link_to "Visit Link", @post.link, class: "button" %>
      <% if @post.user == current_user %>
        <%= link_to 'Edit', edit_post_path(@post), class: "button" %>
        <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: "button" %>
      <% end %>
      <%= link_to like_post_path(@post), method: :get, class: "data" do %>
        <i class="fa fa-thumbs-o-up"></i>
        <%= pluralize(@post.get_upvotes.size, "Like") %>
      <% end %>
      <%= link_to dislike_post_path(@post), method: :get, class: "data" do %>
        <i class="fa fa-thumbs-o-down"></i>
        <%= pluralize(@post.get_downvotes.size, "Dislike") %>
      <% end %>
      <p class="data">
        <i class="fa fa-comments-o"></i>
        <%= pluralize(@post.comments.count, "Comment") %>
      </p>
    </div>
    <% unless @random_post.nil? %>
      <div id="random-post">
        <h3>Random Post</h3>
        <div class="post">
          <div class="post-image">
            <%= link_to (image_tag @random_post.image.url(:small)), post_path(@random_post) %>
          </div>
          <div class="post-content">
            <div class="title">
              <h2><%= link_to @random_post.title, post_path(@random_post) %></h2>
            </div>
            <div class="data clearfix">
              <p class="username">
                Shared by <%= @random_post.user.username %>
              </p>
              <p class="buttons">
                <span>
                  <i class="fa fa-comments-o"></i>
                  <%= @random_post.comments.count %>
                </span>
                <span>
                  <i class="fa fa-thumbs-o-up"></i>
                  <%= @random_post.get_upvotes.size %>
                </span>
              </p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div id="comments">
  <h2 class="comment-count"><%= pluralize(@post.comments.count, "Comment") %></h2>
  <% @comments.each do |comment| %>
    <div class="comment">
      <p class="username"><%= comment.user.username %></p>
      <p class="content"><%= comment.content %></p>
    </div>
  <% end %>
  <%= render 'comments/form' %>
</div>